In [122]:
from sklearn.model_selection import train_test_split
import wandb
from keras.datasets import fashion_mnist
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [123]:
wandb.login()

True

### DOWNLOADING THE DATASET AND PLOTTING ONE SAMPLE IMAGE FROM EACH CLASS

In [ ]:
# start a new wandb run to track this script
wandb.init(
    # set the wandb project where this run will be logged
    project="CS6910_Assignment-1",
)

# simulate training
# x_train is a (60000,28,28) matrix consisting image pixels for training
# y_train is a (60000,1) matrix consisting of labels
# x_test is a (10000,28,28) matrix consisting image pixels for testing
# y_test is a (10000,1) matrix consisting of labels for testing
(x_train, y_train), (x_test, y_test) =fashion_mnist.load_data()
labels=set()
i=0
fig,ax=plt.subplots(2,5,figsize=(10,5))
row=0
col=0
for pixels in x_train:
  #The matplotlib function imshow() creates an image from a 2-dimensional numpy array
  #pixels is (28,28) 2-D array
  #l is the current label of image
  l=y_train[i]
  if(not(l in labels)):
    if(col>=5):
      col=0
      row+=1
    ax[row][col].imshow(pixels,cmap="gray")
    ax[row][col].set_title("Label {}".format(l))
    ax[row][col].axis(False)
    labels.add(l)
    col+=1
  #if we get all our 10 labels just break the loop
  if(len(labels)==10):
    break;
  i+=1
wandb.log({"plot":plt})   
# finish the wandb run, necessary in notebooks
wandb.finish()

## DATA-PREPROCESSING

In [150]:
#RESHAPING THE TRAIN_IMAGE DATASET FROM (60000,28x28) TO (60000,784) AND SAME FOR TEST_IMAGE
num_inputs=784
num_outputs=10
x_train=x_train.reshape(60000,784)
x_test=x_test.reshape(10000,784)

#NORMALIZING THE DATASET
x_train=x_train/255.0
x_test=x_test/255.0

#SPLITTING THE TRAINING DATA FOR VALIDATION AND TESTING
train_x,val_x,train_y,val_y=train_test_split(x_train,y_train)
train_x=np.transpose(train_x)
train_y=np.transpose(train_y)
val_x=np.transpose(val_x)
val_y=np.transpose(val_y)

#ONE-HOT ENCODING FOR Y_TRAIN AND Y_TEST: 
exp_y=np.zeros((10,60000))
exp_y_test=np.zeros((10,10000))
for i in range(0,60000):
    exp_y[y_train[i]][i]=1
for i in range(0,10000):
    exp_y_test[y_test[i]][i]=1

#RESHAPING MY DATA TO COLUMN-WISE IMAGES
x_train=x_train.T
x_test=x_test.T


### ACTIVATION FUNCTIONS

In [151]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-np.clip(x, -500, 500)))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return np.multiply(s, np.subtract(1, s))

def softmax(x):
    x=x-np.max(x)
    return np.exp(x) / np.sum(np.exp(x), axis=0)
# def sigmoid_derivative(x):
#     return sigmoid(x) * (1-sigmoid(x))

### INITIALIZING THE PARAMETERS

In [178]:
#USING XAVIER INITIALIZATION TO INITIALIZE WEIGHTS AND BIAS MATRIX

#INDEXING DONE FROM 1
hidden_layers=3
L=hidden_layers+1 #number of layers excluding hidden layer
neurons=[0,128,128,128]
weights=[0]*(hidden_layers+2)
biases=[0]*(hidden_layers+2)
np.random.seed(42)
for i in range(1,hidden_layers+1):
  n=neurons[i]
  # appending the weight and bias matrix for the ith layer
  if(i==1):
    weights[i]=(np.random.randn(n,784)*np.sqrt(2/(n+784)))
    biases[i]=(np.zeros((n,1)))
    # biases[i]=(np.random.randn(n,1))
  else:
    weights[i]=(np.random.randn(n,neurons[i-1])*np.sqrt(2/(n+neurons[i-1])))
    biases[i]=(np.zeros((n,1)))
    # biases[i]=(np.random.randn(n,1))
weights[L]=(np.random.randn(10,neurons[hidden_layers])*np.sqrt(2/(10+neurons[hidden_layers-1])))
weights=np.array(weights,dtype=object)
biases=np.array(biases,dtype=object)

## FEED FORWARD PROPOGATION

In [172]:
def FeedForwardNetwork(weights,biases,data):
  #Returns the array containing the output probablity for each class the data can belong
  a=[None]*(L+1)
  h=[None]*(L+1)
  h[0]=data
  for i in range(1,L):
    #weight and bias matrix for hidden-layer i
    weight=weights[i]
    bias=biases[i]
    #pre activation
    a[i]=(bias+np.matmul(weight,h[i-1]))
    #post activation
    h[i]=(sigmoid(a[i]))
  #weight and bias matrix for ouput layer
  weight=weights[L]
  bias=biases[L]
  a[L]=(bias+np.matmul(weight,h[L-1]))
  h[L]=softmax(a[L])
  return h[L],h,a

## BACK PROPOGATION

In [173]:
def BackPropogation(weights,H,A,exp_Y,y_hat,batch_size):
  # Input Parameters of function
  # --> Model Parameters: weights and biases
  # --> H: Post-activations, A: Pre-Activations
  # --> exp_Y: Actual Class Labels
  # Returns list of gradients for each layer wrt weights and biases(parameters)
  gradients_H=[0] * (L+1)
  gradients_W=[0] * (L+1)
  gradients_B=[0] * (L+1)
  gradients_A=[0] * (L+1)
  
  #Computing Gradient For The Output Layer(Pre Activation)
  gradients_A[L]=-(exp_Y-y_hat)
  for k in range(L,0,-1):
    #compute gradients of the parameters
    gradients_W[k]=np.matmul(gradients_A[k],np.transpose(H[k-1]))/ batch_size
    gradients_B[k]=np.sum(gradients_A[k], axis=1,keepdims=True)/ batch_size
    #compute gradients of the hidden layers
    gradients_H[k-1]=np.matmul(np.transpose(weights[k]),gradients_A[k])
    if(k>1):
      gradients_A[k-1]=np.multiply(gradients_H[k-1],sigmoid_derivative(A[k-1]))
    

  return gradients_W,gradients_B

In [180]:
epoch=1000
predicted_y=[]
temp_y=np.zeros((10,1000))
for i in range(0,1000):
    temp_y[y_train[i]][i]=1
while epoch>=0:
    eta=0.001
    # print(biases[1].shape)
    output,post_act,pre_act=FeedForwardNetwork(weights,biases,x_train[:,:1000])
    gradients_W,gradients_B=BackPropogation(weights,post_act,pre_act,temp_y,output,1000)
    gradients_B=np.array(gradients_B,dtype=object)
    gradients_W=np.array(gradients_W,dtype=object)
    weights=weights-eta*(gradients_W)
    biases=biases-eta*(gradients_B)
    # print(np.sum(output,axis=0))
    # print(output[:,1])
    predicted_y.append(np.argmax(output,axis=0))
    epoch-=1

## FUNCTIONS FOR UPDATION OF PARAMETERS

In [175]:
def sgd_params_update(weights,biases,gradients_W,gradients_B,eta):
    gradients_B=np.array(gradients_B,dtype=object)
    gradients_W=np.array(gradients_W,dtype=object)
    weights=weights-eta*(gradients_W)
    biases=biases-eta*(gradients_B)
    return weights,biases

### MODEL

In [176]:
batch_size=100
epoch=10
eta=0.01

### STOCHIASTIC GRADIENT DESCENT

In [177]:
count=1
predicted_y=[]
while count<=20:
    for i in range(0,x_train.shape[1],batch_size):
      #Implementing Stochiastic Gradient Descent
      mini_batch=x_train[:,i:i+batch_size]
      output,post_act,pre_act=FeedForwardNetwork(weights,biases,mini_batch)
      gradients_W,gradients_B=BackPropogation(weights,post_act,pre_act,exp_y[:,i:i+batch_size],output,batch_size)
      weights,biases=sgd_params_update(weights,biases,gradients_W,gradients_B,eta)
    # print(output[0])
    full_output,_,_=FeedForwardNetwork(weights,biases,x_train)
    predicted_y.append(np.argmax(full_output,axis=0))
    count+=1
    print(full_output[0])
    print(count)

[0.10125725 0.10125725 0.10125725 ... 0.10125734 0.10125725 0.10125725]
2
[0.10125908 0.10125908 0.10125908 ... 0.10125917 0.10125907 0.10125908]
3
[0.10126089 0.10126089 0.10126089 ... 0.10126098 0.10126089 0.10126089]
4
[0.10126271 0.10126271 0.10126271 ... 0.1012628  0.10126271 0.10126271]
5
[0.10126453 0.10126453 0.10126453 ... 0.10126462 0.10126452 0.10126453]
6
[0.10126634 0.10126634 0.10126634 ... 0.10126643 0.10126633 0.10126634]
7
[0.10126815 0.10126815 0.10126815 ... 0.10126824 0.10126814 0.10126815]
8
[0.10126996 0.10126996 0.10126996 ... 0.10127005 0.10126995 0.10126996]
9
[0.10127176 0.10127176 0.10127176 ... 0.10127186 0.10127176 0.10127176]
10
[0.10127357 0.10127357 0.10127357 ... 0.10127366 0.10127356 0.10127357]
11
[0.10127537 0.10127537 0.10127537 ... 0.10127546 0.10127536 0.10127537]
12
[0.10127717 0.10127717 0.10127717 ... 0.10127726 0.10127716 0.10127717]
13
[0.10127897 0.10127897 0.10127897 ... 0.10127906 0.10127896 0.10127897]
14
[0.10128076 0.10128076 0.10128076

KeyboardInterrupt: ignored

In [182]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
for i in range(0,len(predicted_y)):
    # print(predicted_y[i])
    print("Training accuracy = {} %".format(round(accuracy_score(y_train[:1000], predicted_y[i]) * 100, 3)))

Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training accuracy = 9.5 %
Training acc

In [ ]:
# print(output)
predicted_y_temp=[]
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
output,post_act,pre_act=FeedForwardNetwork(weights,biases,x_test)
predicted_y_temp.append(np.argmax(output,axis=0))
for i in range(0,len(predicted_y_temp)):
    print(predicted_y_temp[i])
    print("Testing accuracy = {} %".format(round(accuracy_score(y_test, predicted_y_temp[i]) * 100, 3)))
# print("Testing accuracy = {} %".format(round(accuracy_score(y_test, predicted_y_test[100]) * 100, 3)))